tasks = [
    { name = "FlushEventOutboxFakeJob", schedule = "1/10 * * * * *" },
    { name = "RefreshAuthCacheFakeJob", schedule = "1/60 * * * * *" },
]

[pubsub]
key_file = "/path/to/google/pubsub-service-account.json"
jobs_topic = "jobs-topic-id"
events_topic = "events-topic-id"

