tasks = [
    # Every 10 seconds
    { name = "FlushEventOutboxJob", schedule = "1/10 * * * * *" },

    # Every minute
    { name = "RefreshAuthCacheJob", schedule = "0 1/1 * * * *" },
]

jwt_secret = "secret"

[pubsub]
key_file = "/path/to/google/pubsub-service-account.json"
topic = "jobs-topic"

